### ISSUE TITLE
Sugar/50_458/back videos incorrect

### ISSUE THREAD

**Issue by sthoduka** [bravebin/Visual-Tactile_Dataset#2]
Hello,
I noticed that the `front_rgb.mp4` videos for Sugar is just a video of an empty table.(https://github.com/tsinghua-rll/Visual-Tactile_Dataset/tree/master/dataset/Suger/50_458/back). The `left_rgb.mp4` videos look correct though. Do you happen to have the correct videos for the front camera?
thanks!

**Comment by wangtaofree** [comment]
Hello, very thanks for found this issue, we really didn't find it before. I've check the origin data we recorded. Unfortunately, the origin video is the same as the video in the dataset, I think it may caused by the camera communication, we didn't find that error when we recording the data, and it only show a static image in the video. Sorry for this issue.

**Comment by sthoduka** [comment]
ok, no problem. Thanks for checking!
